{:user {:plugins [[cider/cider-nrepl "0.17.0"]
                  [venantius/ultra "0.5.2"]
                  [venantius/yagni "0.1.4"]
                  [lein-auto "0.1.3"]
                  [lein-ancient "0.6.15"]
                  [lein-try "0.4.3"]
                  [lein-kibit "0.1.6"]
                  [lein-bikeshed "0.5.1"]]
        :dependencies [[vvvvalvalval/scope-capture "0.2.0"]
                       [com.bhauman/rebel-readline "0.1.4"]
                       [cljfmt "0.5.1"]]
        :aliases {"rebl" ["trampoline" "run" "-m" "rebel-readline.main"]}}}
