"PLUGINS
if filereadable(expand("~/.vimrc.bundles"))
  source ~/.vimrc.bundles
endif

" COLORSCHEME
set background=dark
colorscheme PerfectDark


" Map Ctrl n to open NerdTree
map <C-n> :NERDTreeToggle<CR>

" The Silver Searcher
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
endif

" bind K to grep word under cursor
nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>

" maps leader-t to show tagbar
nmap <leader>t :TagbarToggle<CR>

" CONFIG
" show line numbers
set number
" highlight which line the cursor is on
set cursorline
" load filetype specific indent files
filetype indent plugin on
" visual autocomplete for command menu
set wildmenu
" redraw only when needed
set lazyredraw
" highlights matching parentheses
set showmatch
" search as characters are entered, highlight matches, ignore case except when using capitals
set incsearch
set hlsearch
set ignorecase
set smartcase
" enable syntax highlighting if the terminal has colors
if (&t_Co > 2 || has("gui_running")) && !exists("syntax_on")
  syntax on
endif
" Allow backspacing over autoindent, line breaks and start of insert auto-correction
set backspace=indent,eol,start
" When opening a new line and no filetype-specific indenting is enables, keep the same indent as the line you're currently on.
set autoindent
" Use visualbell instead of beeping when dong something wrong
set visualbell
" enable the use of the mouse for all modes
set mouse=a
" Automatically write before running a command
set autowrite

" SPACES AND TABS
" number of visual spaces per tab
set tabstop=2
" converts tabs to spaces
set expandtab

" MOVEMENT
" move vertically by visual line
nnoremap j gj
nnoremap k gk
" move to beginning and end of line
nnoremap E $
nnoremap B 0
" highlight the last text that was inserted
nnoremap gV `[v`]

" LEADER SHORTCUTS
let mapleader=" "
