[[snippets]]
  description = "[RMQ] Add a new RabbitMQ user"
  command = "rabbitmqctl add_user <user> <pw>"
  output = ""

[[snippets]]
  description = "[RMQ] Create a new RabbitMQ admin user with full permissions"
  command = "rabbitmqctl add_user <user> <password> && rabbitmqctl set_user <user> administrator && rabbitmqctl set_permissions -p / <user> \".*\" \".*\" \".*\""
  output = ""

[[snippets]]
  description = "[RMQ] Make a RabbitMQ virtual host and set permissions"
  command = "rabbitmqctl add_vhost <vhost-name=Some_Virtual_Host> && rabbitmqctl set_permissions -p  <vhost-name=Some_Virtual_Host> <user=guest> \".*\" \".*\" \".*\""
  output = ""

[[snippets]]
  description = "[RMQ] Create a RabbitMQ exchange"
  command = "rabbitmqadmin declare exchange --vhost=<vhost-name=Some_Virtual_Host> name=<exchange-name=some_exchange> type=direct"
  output = ""

[[snippets]]
  description = "[RMQ] Create a RabbitMQ queue"
  command = "rabbitmqadmin declare queue --vhost=<vhost-name=Some_Virtual_Host> name=<queue-name=some_outgoing_queue> durable=true"
  output = ""

[[snippets]]
  description = "[RMQ] Publish a message to a rabbitmq exchange"
  command = "rabbitmqadmin --vhost=<vhost-name=Some_Virtual_Host> publish exchange=<exchange=some_exchange> routing_key=<routing-key=some_routing_key> payload=<payload=\"Hello world\">"
  output = ""

[[snippets]]
  description = "[RMQ] Bind a queue to an exchange"
  command = "rabbitmqadmin --vhost=<vhost-name=Some_Virtual_Host> declare binding source=<exchange-name=some_exchange> destination_type=queue destination=<queue-name=some_outgoing_queue> routing_key=<routing-key=some_routing_key>"
  output = ""

[[snippets]]
  description = "[RMQ] List the RabbitMQ queues present on a particular virtual host"
  command = "rabbitmqctl --vhost=<vhost-name=Some_Virtual_Host> list_queues"
  output = ""

[[snippets]]
  description = "[RMQ] List items held on a particular RabbitMQ queue"
  command = "rabbitmqadmin --vhost=<vhost-name=Some_Virtual_Host> get queue=<queue-name=some_outgoing_queue> count=<how-many-items=3>"
  output = ""

[[snippets]]
  description = "[RMQ] Delete a RabbitMQ queue on a particular vhost"
  command = "rabbitmqadmin --vhost=<vhost-name=Some_Virtual_Host> delete queue name=<queue-name=some_incoming_queue>"
  output = ""

[[snippets]]
  description = "Find and kill a running process"
  command = "ps -ef | grep <process-to-kill> | grep -v grep | awk '{print $2}' | xargs kill -9"
  output = ""

[[snippets]]
  description = "[awk] output non-empty lines from a file; remove any lines that contain a particular pattern; sum the values in columns; print the totals"
  command = "grep . <filename> | grep -v '<remove-lines-with-pattern>' | awk '{s+=<column-to-variable=$3>; r+=<other-column-to-variable=$5>} END {print s; print r}'"
  output = ""

[[snippets]]
  description = "[macos] Restart video utilities on OS X (for when camera is on but video is black)"
  command = "sudo killall VDCAssistant && sudo killall AppleCameraAssistant"
  output = ""

[[snippets]]
  description = "Add a meaningful name to the screen session"
  command = "screen -S <session-name=SCREEN_NAME>"
  output = ""

[[snippets]]
  description = "Get the <pid>.<session-name> for the current session with controlling terminal"
  command = "screen -ls | grep Attached | cut -f2"
  output = ""

[[snippets]]
  description = "Send a specified command to the running screen instance (in this case wait for input to be sent from vim-slime)"
  command = "screen -X eval <command=\"msgwait 0\">"
  output = ""
